# installer for the forecast demonstration skin
# $Id$

from setup import Installer

def loader():
    return ForecastSkinInstaller()

class ForecastSkinInstaller(Installer):
    def __init__(self):
        super(Installer, self).__init__(
            version="0.2",
            name='forecast-skin',
            description='A skin that demonstrates how to use forecast data.',
            author="Matthew Wall",
            author_email="mwall@users.sourceforge.net",
            config={
                'StdReport': {
                    'forecast': {
                        'skin':'forecast',
                        'HTML_ROOT':'forecast' }}},
            data_files=[('skins/forecast',
                         ['skins/forecast/skin.conf',
                          'skins/forecast/forecast.inc',
                          'skins/forecast/index.html.tmpl']),
                        ('skins/forecast/icons',
                         ['skins/forecast/icons/AF.png',
                          'skins/forecast/icons/B1.png',
                          'skins/forecast/icons/B1n.png',
                          'skins/forecast/icons/B2.png',
                          'skins/forecast/icons/B2n.png',
                          'skins/forecast/icons/BD.png',
                          'skins/forecast/icons/BK.png',
                          'skins/forecast/icons/BKn.png',
                          'skins/forecast/icons/BS.png',
                          'skins/forecast/icons/CL.png',
                          'skins/forecast/icons/CLn.png',
                          'skins/forecast/icons/E.png',
                          'skins/forecast/icons/F+.png',
                          'skins/forecast/icons/F.png',
                          'skins/forecast/icons/FW.png',
                          'skins/forecast/icons/FWn.png',
                          'skins/forecast/icons/H.png',
                          'skins/forecast/icons/K.png',
                          'skins/forecast/icons/N.png',
                          'skins/forecast/icons/NE.png',
                          'skins/forecast/icons/NW.png',
                          'skins/forecast/icons/OV.png',
                          'skins/forecast/icons/OVn.png',
                          'skins/forecast/icons/PF+.png',
                          'skins/forecast/icons/PF.png',
                          'skins/forecast/icons/S.png',
                          'skins/forecast/icons/SC.png',
                          'skins/forecast/icons/SCn.png',
                          'skins/forecast/icons/SE.png',
                          'skins/forecast/icons/SW.png',
                          'skins/forecast/icons/W.png',
                          'skins/forecast/icons/blizzard.png',
                          'skins/forecast/icons/drizzle.png',
                          'skins/forecast/icons/flag-yellow.png',
                          'skins/forecast/icons/flag.png',
                          'skins/forecast/icons/flurries.png',
                          'skins/forecast/icons/frzngdrzl.png',
                          'skins/forecast/icons/moon.png',
                          'skins/forecast/icons/moonphase.png',
                          'skins/forecast/icons/moonriseset.png',
                          'skins/forecast/icons/pop.png',
                          'skins/forecast/icons/rain.png',
                          'skins/forecast/icons/raindrop.png',
                          'skins/forecast/icons/rainshwrs.png',
                          'skins/forecast/icons/raintorrent.png',
                          'skins/forecast/icons/sleet.png',
                          'skins/forecast/icons/snow.png',
                          'skins/forecast/icons/snowflake.png',
                          'skins/forecast/icons/snowshwrs.png',
                          'skins/forecast/icons/sprinkles.png',
                          'skins/forecast/icons/sun.png',
                          'skins/forecast/icons/sunmoon.png',
                          'skins/forecast/icons/sunriseset.png',
                          'skins/forecast/icons/thermometer-blue.png',
                          'skins/forecast/icons/thermometer-dewpoint.png',
                          'skins/forecast/icons/thermometer-red.png',
                          'skins/forecast/icons/thermometer.png',
                          'skins/forecast/icons/triangle-down.png',
                          'skins/forecast/icons/triangle-right.png',
                          'skins/forecast/icons/tstms.png',
                          'skins/forecast/icons/water.png']),
                        ]
            )
